question 3 part 1

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('iris.txt')
print(df)

     sepal length  sepal width  petal length  petal width      Iris plant
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [3]:
X=df.drop("Iris plant", axis=1).values
n, d = X.shape
C = np.cov(X, rowvar=False)
print("(a) Covariance Matrix:\n", C)

(a) Covariance Matrix:
 [[ 0.68569351 -0.03926846  1.27368233  0.5169038 ]
 [-0.03926846  0.18800403 -0.32171275 -0.11798121]
 [ 1.27368233 -0.32171275  3.11317942  1.29638747]
 [ 0.5169038  -0.11798121  1.29638747  0.58241432]]


In [4]:
corr_matrix = np.corrcoef(X, rowvar=False)
triu_indices = np.triu_indices(d, k=1)
corr_values = corr_matrix[triu_indices]
print(corr_matrix)

[[ 1.         -0.10936925  0.87175416  0.81795363]
 [-0.10936925  1.         -0.4205161  -0.35654409]
 [ 0.87175416 -0.4205161   1.          0.9627571 ]
 [ 0.81795363 -0.35654409  0.9627571   1.        ]]


In [5]:
max_corr_idx = np.argmax(corr_values)
min_corr_idx = np.argmin(corr_values)

In [6]:
feature_names = df.columns
pairs = list(zip(triu_indices[0], triu_indices[1]))

print("\n(b) Most positively correlated features:",
      (feature_names[pairs[max_corr_idx][0]], feature_names[pairs[max_corr_idx][1]]),
      "with correlation =", corr_values[max_corr_idx])

print("Most negatively correlated features:",
      (feature_names[pairs[min_corr_idx][0]], feature_names[pairs[min_corr_idx][1]]),
      "with correlation =", corr_values[min_corr_idx])

print("Least correlated (closest to 0):",
      (feature_names[pairs[np.argmin(np.abs(corr_values))][0]],
       feature_names[pairs[np.argmin(np.abs(corr_values))][1]]),
      "with correlation =", corr_values[np.argmin(np.abs(corr_values))])


(b) Most positively correlated features: ('petal length', 'petal width') with correlation = 0.9627570970509659
Most negatively correlated features: ('sepal width', 'petal length') with correlation = -0.42051609640115445
Least correlated (closest to 0): ('sepal length', 'sepal width') with correlation = -0.1093692499506493


In [11]:
df2=df.drop('Iris plant',axis=1)
means =df2.mean()
variances = df2.var(ddof=1)  # sample variance (ddof=1)
print("\n(c) Sample means:\n", means)
print("Sample variances:\n", variances)


(c) Sample means:
 sepal length    5.843333
sepal width     3.054000
petal length    3.758667
petal width     1.198667
dtype: float64
Sample variances:
 sepal length    0.685694
sepal width     0.188004
petal length    3.113179
petal width     0.582414
dtype: float64


In [12]:
eigenvalues, eigenvectors = np.linalg.eigh(C)  # eigh since C is symmetric
print("\n(d) Eigenvalues of covariance matrix:\n", eigenvalues)


(d) Eigenvalues of covariance matrix:
 [0.02368303 0.07852391 0.24224357 4.22484077]
